server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /team6 {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }
    
    location / {
        proxy_pass http://k8s-msaservices-7d023f0bb9-676035063.ap-northeast-2.elb.amazonaws.com/team6/;
        try_files $uri $uri/ /index.html;
    }
}
